const CONFIG={SHEET_ID:'1-ghFaPLJCAAgs9mcKXnBxXz9ycf8z5Ja-fVeGU4SNao',MASTER_SHEET:'MT SISWA MAPEL',DB_SHEET:'DB_KLINIK_PILIHAN',API_URL:'https://script.google.com/macros/s/AKfycbx23izdGlUWNU3217-Zxv7NaW79nkgky-h4lCO4KHgqftuSWrXc74qywm7v8_SDeDnDTw/exec'};
let master={mt:[],mapel:[],s11:[],s12:[]},rows=[];
const $=id=>document.getElementById(id);
function unique(a){return [...new Set(a.filter(v=>String(v).trim()).map(v=>String(v).trim()))].sort((a,b)=>a.localeCompare(b,'id'))}
function setOptions(el,items,placeholder='Pilih…'){if(!el)return;el.innerHTML=`<option value="">${placeholder}</option>`+items.map(x=>`<option>${esc(x)}</option>`).join('')}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function formatDate(v){const s=String(v??'').trim();if(!s)return '';let m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(m)return `${m[3].padStart(2,'0')}/${m[2].padStart(2,'0')}/${m[1]}`;m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(m)return `${m[1].padStart(2,'0')}/${m[2].padStart(2,'0')}/${m[3]}`;return s}
function dateKey(v){const s=String(v??'').trim();let m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(m)return `${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(m)return `${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;return s}
function apiJsonp(action,extra={}){return new Promise((resolve,reject)=>{const cb='__klinikCb_'+Date.now()+'_'+Math.random().toString(36).slice(2);const script=document.createElement('script');const params=new URLSearchParams({action,callback:cb,_:Date.now(),...extra});let timer=setTimeout(()=>{cleanup();reject(new Error('API Google Sheets tidak merespons.'))},15000);function cleanup(){clearTimeout(timer);delete window[cb];script.remove()}window[cb]=data=>{cleanup();if(!data||!data.ok){reject(new Error(data?.error||'API mengembalikan error.'));return}resolve(data)};script.onerror=()=>{cleanup();reject(new Error('API Google Sheets tidak dapat diakses.'))};script.src=`${CONFIG.API_URL}?${params.toString()}`;document.head.appendChild(script)})}
async function apiGet(action){const data=await apiJsonp(action);return data.rows||[]}
function studentsForClass(k){return k==='11'?master.s11:k==='12'?master.s12:unique([...master.s11,...master.s12])}
function updateStudentFilter(){const el=$('filterStudent');if(!el)return;const current=el.value;const list=studentsForClass($('filterClass')?.value);setOptions(el,list,'Semua');if(list.includes(current))el.value=current}
function updateDateFilter(){const el=$('filterDate');if(!el)return;const current=el.value;const dates=unique(rows.map(r=>formatDate(r.date))).sort((a,b)=>dateKey(b).localeCompare(dateKey(a)));setOptions(el,dates,'Semua');if(dates.includes(current))el.value=current}
function setRefreshText(text){const btn=$('refreshBtn');if(!btn)return;const span=btn.querySelector('span');if(span)span.textContent=text;else btn.textContent=text}
async function load(){const btn=$('refreshBtn');if(btn){btn.classList.add('loading');setRefreshText('Refreshing')}try{const m=await apiGet('master');master.mt=unique(m.slice(1).map(r=>r[0]));master.mapel=unique(m.slice(1).map(r=>r[1]));master.s11=unique(m.slice(1).map(r=>r[2]));master.s12=unique(m.slice(1).map(r=>r[3]));setOptions($('mtSelect'),master.mt);setOptions($('subjectSelect'),master.mapel);setOptions($('filterMt'),master.mt,'Semua');setOptions($('filterSubject'),master.mapel,'Semua');updateStudentFilter();try{const d=await apiGet('db');rows=d.slice(1).filter(r=>r.some(Boolean)).map(r=>({id:r[0],date:r[1],kelas:r[2],siswa:r[3],mapel:r[4],mt:r[5],kuis:r[6],post:r[7]}))}catch(e){rows=[]}updateDateFilter();renderAll();toast('Data berhasil diperbarui.')}catch(e){toast(e.message);if($('studentHint'))$('studentHint').textContent='Data master belum dapat dimuat.'}finally{if(btn){btn.classList.remove('loading');setRefreshText('Refresh')}}}
function renderAll(){const sessions=new Set(rows.map(r=>`${dateKey(r.date)}|${r.kelas}|${r.mapel}|${r.mt}`)).size;const students=new Set(rows.map(r=>r.siswa)).size;const q=nums(rows.map(r=>r.kuis)),p=nums(rows.map(r=>r.post));if($('kpiSessions'))$('kpiSessions').textContent=sessions||0;if($('kpiStudents'))$('kpiStudents').textContent=students||0;if($('kpiQuiz'))$('kpiQuiz').textContent=avg(q);if($('kpiPost'))$('kpiPost').textContent=avg(p);const counts={};const uniqueMapelDates=new Set();rows.forEach(r=>{const key=`${dateKey(r.date)}|${r.mapel}`;if(!uniqueMapelDates.has(key)){uniqueMapelDates.add(key);counts[r.mapel]=(counts[r.mapel]||0)+1}});const list=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,7);const max=list[0]?.[1]||1;const subjectList=$('subjectList');if(subjectList)subjectList.innerHTML=list.length?list.map(([n,c])=>`<div class="barrow"><span>${esc(n)}</span><div class="track"><div class="fill" style="width:${c/max*100}%"></div></div><b>${c}</b></div>`).join(''):'<div class="empty">Belum ada data sesi.</div>';renderTable()}
function nums(a){return a.map(Number).filter(Number.isFinite)}function avg(a){return a.length?avgN(a).toFixed(1):'—'}function avgN(a){return a.reduce((x,y)=>x+y,0)/a.length}
function renderStudents(){const k=$('classSelect')?.value;const list=k==='11'?master.s11:k==='12'?master.s12:[];const hint=$('studentHint'),table=$('studentTable');if(hint)hint.textContent=list.length?`${list.length} siswa tersedia.`:'Pilih kelas untuk menampilkan siswa.';if(!table)return;if(!list.length){table.innerHTML='<div class="empty">Belum ada siswa.</div>';return}table.innerHTML='<div class="student-row head"><span></span><span>Nama Siswa</span><span>Nilai Kuis</span><span>Nilai Post Test</span></div>'+list.map((s,i)=>`<div class="student-row"><input class="pick" type="checkbox" data-i="${i}"><span>${esc(s)}</span><input class="quiz" type="number" min="0" max="100" step="1" placeholder="0–100"><input class="post" type="number" min="0" max="100" step="1" placeholder="0–100"></div>`).join('')}
function renderTable(){const body=$('dataBody');if(!body)return;const fd=$('filterDate')?.value,fc=$('filterClass')?.value,fs=$('filterSubject')?.value,fm=$('filterMt')?.value,fu=$('filterStudent')?.value;const data=rows.filter(r=>(!fd||formatDate(r.date)===fd)&&(!fc||String(r.kelas)===fc)&&(!fs||r.mapel===fs)&&(!fm||r.mt===fm)&&(!fu||r.siswa===fu)).slice().reverse();body.innerHTML=data.length?data.map(r=>`<tr><td>${esc(formatDate(r.date))}</td><td>${esc(r.kelas)}</td><td>${esc(r.siswa)}</td><td>${esc(r.mapel)}</td><td>${esc(r.mt)}</td><td>${esc(r.kuis)}</td><td>${esc(r.post)}</td></tr>`).join(''):'<tr><td colspan="7" class="empty">Belum ada data.</td></tr>'}
function toast(t){const x=$('toast');if(!x)return;x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),3000)}
function setup(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');const page=$(b.dataset.tab);if(page)page.classList.add('active')});document.querySelectorAll('[data-go="input"]').forEach(b=>b.onclick=()=>document.querySelector('[data-tab="input"]')?.click());if($('classSelect'))$('classSelect').onchange=renderStudents;if($('selectAll'))$('selectAll').onclick=()=>document.querySelectorAll('.pick').forEach(x=>x.checked=true);if($('refreshBtn'))$('refreshBtn').onclick=()=>load();if($('filterDate'))$('filterDate').onchange=renderTable;if($('filterClass'))$('filterClass').onchange=()=>{updateStudentFilter();renderTable()};['filterSubject','filterMt','filterStudent'].forEach(id=>{if($(id))$(id).onchange=renderTable});if($('sessionForm'))$('sessionForm').onsubmit=async e=>{e.preventDefault();const picked=[...document.querySelectorAll('.student-row:not(.head)')].filter(r=>r.querySelector('.pick')?.checked);if(!picked.length){toast('Pilih minimal satu siswa.');return}if(!$('mtSelect')?.value||!$('subjectSelect')?.value||!$('classSelect')?.value||!$('date')?.value){toast('Lengkapi tanggal, kelas, MT, dan mapel.');return}const payload={date:$('date').value,kelas:$('classSelect').value,mt:$('mtSelect').value,mapel:$('subjectSelect').value,students:picked.map(r=>({siswa:r.children[1].textContent.trim(),kuis:r.querySelector('.quiz').value,post:r.querySelector('.post').value}))};try{if($('saveStatus'))$('saveStatus').textContent='Menyimpan…';const result=await apiJsonp('save',{payload:JSON.stringify(payload)});if($('saveStatus'))$('saveStatus').textContent=`Tersimpan ✓ (${result.count} siswa)`;toast('Data berhasil disimpan.');$('sessionForm').reset();if($('date'))$('date').value=new Date().toISOString().slice(0,10);renderStudents();setTimeout(load,500)}catch(err){if($('saveStatus'))$('saveStatus').textContent='Gagal menyimpan';toast(err.message)}};if($('date'))$('date').value=new Date().toISOString().slice(0,10)}
setup();load();